name: RandomSpawn
version: @version@
main: Main.Main
api-version: @api-version@
authors: [ MEL_TEN, dalbodeule ]
description: RandomSpawn
commands:
  rsp:
    description: player random spawn
    usage: /rsp