name: RandomSpawn
version: @version@
main: io.github.mel_ten.randomspawn.RandomSpawn
api-version: @api-version@
authors: [ MEL_TEN, dalbodeule ]
description: RandomSpawn
commands:
  rsp:
    description: player random spawn
    usage: /rsp